sudo: required

services:
    - docker

before_install:
    - docker pull rootproject/root-ubuntu16
    - docker images


script:
#Compile it
    - docker run  -v $PWD:~  --rm -it --user $(id -u) $image /bin/bash -c "cd ~;make all"

