sudo: required

services:
    - docker

before_install:
    - docker pull rootproject/root-ubuntu16
    - docker images


script:
#Compile it
    - ./rd make all test
    - ./rd ./test && mv testGrid.pdf  testGrid1.pdf
    - ./rd root -l -b -q test.C && mv testGrid.pdf  testGrid2.pdf
    - ./rd root -l -b -q test2.C && mv testGrid.pdf  testGrid3.pdf
    - ./rd python test.py 
    - mkdir public && cp *.pdf public

deploy:
  provider: pages
  local-dir : public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master

